version: '3.8'

services:
  db:
    image: postgres:15
    container_name: loan_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: loan_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_FLYWAY_ENABLED: 'true'
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: 'true'
      SPRING_APPLICATION_NAME: api
    depends_on:
      - db
    ports:
      - "8080:8080"

  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: loan_application
    ports:
      - "4200:4200"
    depends_on:
      - server

volumes:
  pgdata:
